Quick sanity check: how are different models currently embedding certain users? \
(big matrix only, to prevent leakage)

In [1]:
# Load in big matrix

import deep_linear_bandits.data as dlb_data

DLB_DIR = "/home/sulay/deep-linear-bandits/"

big_train, _ = dlb_data.preprocess_krbig_interactions(data_dir=DLB_DIR+"kuairec/data/")

In [ ]:
# Get item popularities in big matrix

import numpy as np
import pandas as pd

item_popularity = dlb_data.compute_item_popularity(data_dir=DLB_DIR+"kuairec/data/")

array([13.,  1., 13., ...,  1.,  4.,  2.], shape=(10728,))

In [44]:
# Show items sorted by global popularity

pd.DataFrame({
    'global_popularity': item_popularity
}).sort_values(by=['global_popularity'], ascending=False)

       global_popularity
314               2559.0
7383              2332.0
8298              2253.0
8366              1967.0
3400              1829.0
5464              1802.0
2123              1582.0
2894              1579.0
6787              1500.0
211               1485.0
4040              1481.0
4123              1455.0
...                  ...
8645                 0.0
4615                 0.0
9003                 0.0
9011                 0.0
4423                 0.0
8861                 0.0
874                  0.0
10601                0.0
6216                 0.0
6218                 0.0
10669                0.0
4                    0.0

[10728 rows x 1 columns]

In [71]:
# Get all user & item embeddings for a specific MODEL

import deep_linear_bandits.two_tower as dlb_tt
import torch
import pickle

pd.set_option('display.min_rows', 25)

NUM_USERS = 7176
NUM_ITEMS = 10728

MODEL = "lr-5em4"

torch.set_float32_matmul_precision('high')
device = (
    torch.accelerator.current_accelerator()
    if torch.accelerator.is_available()
    else torch.device('cpu')
)

with open(DLB_DIR + f"tt-models/{MODEL}/model_args.pkl", "rb") as f:
    model_args = pickle.load(f)
model = dlb_tt.TwoTower(**model_args).to(device)
model.load_state_dict(
    torch.load(
        DLB_DIR + f"tt-models/{MODEL}/model.pt",
        map_location=device,
        weights_only=True
    )
)
model.eval()

with torch.inference_mode():
    """
    Retrieve embeddings for all users & items in the big matrix
    """
    user_ids = torch.arange(0, NUM_USERS, device=device, dtype=torch.long)
    (user_cat_feats, _), user_numeric_feats = dlb_data.preprocess_user_features(data_dir=DLB_DIR+"kuairec/data/")
    user_cat_feats = torch.tensor(user_cat_feats, dtype=torch.long, device=device)
    user_numeric_feats = torch.tensor(user_numeric_feats, dtype=torch.float32, device=device)

    user_embeddings = model.user_tower(user_ids, user_cat_feats, user_numeric_feats).cpu().numpy()

    item_ids = torch.arange(0, NUM_ITEMS, device=device, dtype=torch.long)
    item_categories = dlb_data.preprocess_item_categories(data_dir=DLB_DIR+"kuairec/data/").to(device)

    item_embeddings = model.item_tower(item_ids, item_categories).cpu().numpy()

In [72]:
# What's a specific user U's top items in the big matrix?
# (from training, avoid leakage of val)

U = 1376 # (recall users are between 0 and 7175)

U_wrs = big_train[big_train.user_id == U].sort_values(by='watch_ratio', ascending=False)
U_wrs = U_wrs.rename(columns = {'video_id': 'item_id'})

# What's the model currently got as the top items for that user?
# user_embeddings: (7176, D); for one user it's (D,)
# item_embeddings: (10728, D)
item_scores = item_embeddings @ user_embeddings[U, :]
top_items = np.argsort(item_scores)[::-1]
top_items_scores = item_scores[top_items]

df = pd.DataFrame({
    'item_id': top_items,
    'model_similarity': top_items_scores
})

# Top items by model similarity, and the actual watch_ratio (+ item popularity)
top_model = df.merge(right=U_wrs, on='item_id')
top_model['global_popularity'] = item_popularity[top_model.item_id.values]
top_model

      item_id  model_similarity  user_id  watch_ratio  global_popularity
0         314          0.762838     1376     2.399087             2559.0
1        5464          0.760125     1376     1.774618             1802.0
2        4040          0.743471     1376     2.753567             1481.0
3        8298          0.733474     1376     2.102752             2253.0
4        4123          0.728501     1376     1.582484             1455.0
5        3400          0.727410     1376     2.256117             1829.0
6        2123          0.721359     1376     1.610614             1582.0
7         154          0.718464     1376     2.291443             1322.0
8        2894          0.716359     1376     1.399328             1579.0
9        5434          0.712953     1376     2.527463             1193.0
10       1894          0.706937     1376     2.986958              658.0
11       2343          0.703232     1376     2.120582             1080.0
...       ...               ...      ...          ...                ...
1958     7224         -0.026674     1376     0.136141                2.0
1959     2854         -0.032762     1376     0.117467                4.0
1960     7461         -0.038659     1376     0.042014                2.0
1961     7700         -0.042222     1376     0.159499                3.0
1962     1540         -0.043612     1376     0.063172               11.0
1963     6233         -0.046069     1376     0.045184                1.0
1964     9709         -0.060873     1376     0.069663                3.0
1965     8391         -0.069654     1376     0.231798                3.0
1966     7096         -0.090432     1376     0.053856                2.0
1967     5576         -0.101706     1376     0.105469                1.0
1968    10567         -0.115103     1376     0.228773                1.0
1969     7126         -0.143328     1376     0.091403                4.0

[1970 rows x 5 columns]

In [73]:
# Top items by their actual watch_ratio; index will be where the model is actually placing them
top_model.sort_values(by=['watch_ratio'], ascending=False)

      item_id  model_similarity  user_id  watch_ratio  global_popularity
512     10184          0.406994     1376     7.392721              430.0
26       6463          0.661792     1376     6.188506              464.0
24       3401          0.664566     1376     4.419501              617.0
1486      867          0.328030     1376     3.951360              115.0
1194     5738          0.366673     1376     3.612493               97.0
522      2110          0.406189     1376     3.318202               16.0
1453     7296          0.338547     1376     3.276265               51.0
1185     4261          0.367285     1376     3.173942              162.0
660      4425          0.396986     1376     3.097894              140.0
10       1894          0.706937     1376     2.986958              658.0
2        4040          0.743471     1376     2.753567             1481.0
67       8992          0.578129     1376     2.734576              143.0
...       ...               ...      ...          ...                ...
524      7714          0.405897     1376     0.000000              177.0
538      4724          0.404874     1376     0.000000              189.0
797      4586          0.388572     1376     0.000000              177.0
1036    10371          0.375763     1376     0.000000              101.0
841      2661          0.386333     1376     0.000000              163.0
665      7501          0.396589     1376     0.000000              148.0
623      9987          0.399094     1376     0.000000              264.0
1081     8559          0.374012     1376     0.000000               80.0
336      4305          0.423229     1376     0.000000              230.0
480      7330          0.409440     1376     0.000000              208.0
1743     8606          0.237205     1376     0.000000               42.0
92       4858          0.542032     1376     0.000000             1083.0

[1970 rows x 5 columns]

In [74]:
# Top items by their global popularity, index is where the model is placing them
top_model.sort_values(by=['global_popularity'], ascending=False)

      item_id  model_similarity  user_id  watch_ratio  global_popularity
0         314          0.762838     1376     2.399087             2559.0
3        8298          0.733474     1376     2.102752             2253.0
5        3400          0.727410     1376     2.256117             1829.0
1        5464          0.760125     1376     1.774618             1802.0
6        2123          0.721359     1376     1.610614             1582.0
8        2894          0.716359     1376     1.399328             1579.0
2        4040          0.743471     1376     2.753567             1481.0
4        4123          0.728501     1376     1.582484             1455.0
25       1709          0.663873     1376     2.021032             1434.0
13       2130          0.697039     1376     2.723297             1417.0
53       3344          0.602863     1376     1.112470             1335.0
7         154          0.718464     1376     2.291443             1322.0
...       ...               ...      ...          ...                ...
1909     3142          0.081208     1376     0.634379                2.0
1898     4194          0.103859     1376     0.042460                2.0
1891       59          0.114405     1376     1.100090                2.0
1871     1461          0.138429     1376     0.121662                2.0
1941     7819          0.033894     1376     0.081305                1.0
1945    10140          0.021699     1376     0.041701                1.0
1948    10189          0.010541     1376     0.066119                1.0
1889     4279          0.119239     1376     0.692500                1.0
1860     9036          0.153511     1376     1.480926                1.0
1963     6233         -0.046069     1376     0.045184                1.0
1967     5576         -0.101706     1376     0.105469                1.0
1968    10567         -0.115103     1376     0.228773                1.0

[1970 rows x 5 columns]